### ISSUE TITLE
DbConnection vs IDbConnection

### ISSUE THREAD

**Issue by akoylu** [codeapologist/DataAbstractions.Dapper#3]
https://github.com/codeapologist/DataAbstractions.Dapper/blob/0e6368a08f98872e08848bacb3b002b2089777ba/src/DataAbstractions.Dapper/DataAccessor.cs#L11

Please correct me if I am wrong, you are restricting the developer to use Microsoft provided DbConnections. In my case I am using an OracleConnection which is provided by Oracle and implements IDbConnection. I suppose you can change constructor signature to take an IDbConnection.

**Comment by codeapologist** [comment]
Hi, please see the discussion here about this topic: https://github.com/codeapologist/DataAbstractions.Dapper/pull/2#issuecomment-481064252

In addition to that, to create a database driver for ADO.NET (which Dapper uses internally) your connection must inherit from DbConnection, and OracleConnection does derive from DbConnection: https://docs.oracle.com/cd/B28359_01/win.111/b28375/OracleConnectionClass.htm

**Comment by codeapologist** [comment]
I decided to favor using IDbConnection.  See my comment here: https://github.com/codeapologist/DataAbstractions.Dapper/pull/2#issuecomment-1019382602
