### ISSUE TITLE
IDataReader parsing

### ISSUE THREAD

**Issue by ltk-mpadelsky** [codeapologist/DataAbstractions.Dapper#4]
Is there any way you could add a mockable interface to replace the IDataReader, returned by ExecuteReader methods?

There are more extension methods applied to this type by the source Dapper library.
For instance, below:
`return dataReader.Parse<T>();`
where dataReader is an IDataReader

Parse is an extension method defined by dapper

**Comment by codeapologist** [comment]
Thanks for the feedback!  I'll work on an implementation to abstract IDataReader.  This will be a breaking change.

**Comment by codeapologist** [comment]
Implemented an abstraction for IDataReader in the 3.1.0 release.  This ended up not being a breaking change as I wanted to preserve the existing method signatures.  I added an additional method to convert an IDataReader to an IDataReaderAccessor.  There is an example of its usage in the README.
